name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update && sudo apt-get install -y docker.io

      - name: Verify Docker installation
        run: docker --version

      - name: Add user to Docker group
        run: sudo usermod -aG docker $USER

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          cd wizdesk  
          docker build -t website .
          cd Server
          docker build -t server .
          docker push website:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1

      - name: Apply Kubernetes Configuration
        run: echo ${{ secrets.KUBECONFIG }} | base64 --decode > kubeconfig.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s-deployment.yaml
